# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/iso" =
    { device = "/dev/mapper/ventoy";
      fsType = "iso9660";
    };

  fileSystems."/nix/.ro-store" =
    { device = "/iso/nix-store.squashfs";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/nix/.rw-store" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/nix/store" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/mnt" =
    { device = "/dev/mapper/mock-noxian";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/mnt/home" =
    { device = "/dev/mapper/mock-noxian";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/mnt/nix" =
    { device = "/dev/mapper/mock-noxian";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/mnt/persist" =
    { device = "/dev/mapper/mock-noxian";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/mnt/flat" =
    { device = "/dev/mapper/mock-noxian";
      fsType = "btrfs";
    };

  fileSystems."/mnt/boot" =
    { device = "/dev/disk/by-uuid/92C1-A920";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/media/motivation/Computer" =
    { device = "/dev/mapper/mock-motivation";
      fsType = "btrfs";
      options = [ "subvol=Computer" ];
    };

  fileSystems."/mnt/media/motivation/Games" =
    { device = "/dev/mapper/mock-motivation";
      fsType = "btrfs";
      options = [ "subvol=Games" ];
    };

  fileSystems."/mnt/media/motivation/Media" =
    { device = "/dev/mapper/mock-motivation";
      fsType = "btrfs";
      options = [ "subvol=Media" ];
    };

  fileSystems."/mnt/media/motivation/Temp" =
    { device = "/dev/mapper/mock-motivation";
      fsType = "btrfs";
      options = [ "subvol=Temp" ];
    };

  fileSystems."/mnt/media/motivation/Learning" =
    { device = "/dev/mapper/mock-motivation";
      fsType = "btrfs";
      options = [ "subvol=Learning" ];
    };

  fileSystems."/mnt/media/motivation/Edit" =
    { device = "/dev/mapper/mock-motivation";
      fsType = "btrfs";
      options = [ "subvol=Edit" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/mock-fang"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
