/*
# ============================================================================
# USER CONFIGURATION FILE
# ============================================================================
# This file allows you to customize various system features and preferences.
# Generated by SpidyNix.sh on $(date)
# This file is automatically managed by the SpidyNix configuration system.
*/

{
  myConfig = {
    /*
    # ============================================================================
    # EDITORS - Choose which code editors to install
    # ============================================================================
    */
    editors = {
      helix = true;     # Fast modal editor (default)
      neovim = false;   # Vim-based editor
      vscode = false;   # Visual Studio Code
      zed = false;      # Zed editor
    };

    /*
    # ============================================================================
    # BROWSERS - Choose which web browsers to install
    # ============================================================================
    */
    browsers = {
      chromium = false; # Chromium browser
      qutebrowser = false; # Keyboard-driven browser
      zen = true;      # Zen browser (Firefox-based)
    };

    /*
    # ============================================================================
    # TERMINALS - Choose which terminal emulators to install
    # ============================================================================
    */
    terminals = {
      kitty = true;     # GPU-accelerated terminal (default)
    };

    /*
    # ============================================================================
    # WINDOW MANAGER - Choose your window manager
    # ============================================================================
    */
    wm = {
      niri = true;      # Niri window manager (default)
    };

    /*
    # ============================================================================
    # FEATURES - Enable/disable major feature sets
    # ============================================================================
    */
    virtualization = true;   # VM and container tools
    gaming = true;           # Gaming-related software

    /*
    # ============================================================================
    # PRODUCTIVITY - Professional creative tools
    # ============================================================================
    */
    productivity = {
      davinciResolve = false;     # Video editing software
      davinciResolveStudio = true; # Full DaVinci Resolve Studio
    };

    /*
    # ============================================================================
    # HARDWARE TYPE - Choose your hardware configuration
    # ============================================================================
    */
    hardwareType = {
      intel = true;     # Intel CPU/GPU (default)
      amd = false;      # AMD CPU/GPU
      nvidia = false;   # NVIDIA GPU
      vm = false;       # Virtual Machine
    };

    /*
    # ============================================================================
    # VIRTUALIZATION TOOLS - Individual virtualization components
    # ============================================================================
    */
    virtualizationTools = {
      libvirt = true;    # Enable libvirt/QEMU/KVM for virtual machines
      docker = true;    # Enable Docker container runtime (conflicts with podman)
      podman = true;     # Enable Podman container runtime
      waydroid = true;  # Enable Waydroid Android emulation
    };

    /*
    # ============================================================================
    # SYSTEM PREFERENCES - User-configurable system settings
    # ============================================================================
    */
    systemPrefs = {
      # Change your timezone (run 'timedatectl list-timezones' to see options)
      timezone = "Asia/Singapore";  # Examples: "America/New_York", "Europe/London", "Asia/Tokyo"

      # Change your keyboard layout (fallback for when not using keyd)
      keyboard = {
        layout = "us";        # Examples: "us", "gb", "de", "fr"
        variant = "qwerty";  # Examples: "colemak", "dvorak", "qwerty"
      };
    };
  };
}
